POST http://localhost:3000/api/login
Content-Type: application/json

{
  "login": "+79629320354",
  "password": "AnusPerdanus123Zhopa!",
  "type": "ACTION"
}

###
POST http://localhost:3000/trigger
Content-Type: application/json

{
  "id": 610201209
}

###
GET http://localhost:3000/api/status
Accept: application/json

###
POST http://localhost:3000/api/enable
Content-Type: application/json

{
  "isEnabled": true
}

###
